### PR TITLE
Update swagger.js

### PR DESCRIPTION
**Pull request by sanmoy27**

### CODE REVIEW

**Comment by sanmoy27** [comment]
let me know if it is fine

**Comment by sanmoy27** [comment]
example:{type: String, required: true, paramType: 'body'}

**Comment by sanmoy27** [comment]
supamii the update swagger code in github isn't being published in npm,
when I am doing npm install the old code is getting installed

**Comment by supamii** [comment]
This has been updated - let me know if you still have issues with it.  thanks for your patience! 

    On Wednesday, December 21, 2016 9:04 AM, sanmoy27 <notifications@github.com> wrote:
 

 supamii the update swagger code in github isn't being published in npm,
when I am doing npm install the old code is getting installed

**Pull request merged**
